package com.citiustech.mrr;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Chase implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("MemberName")
	private java.lang.String member;

	@org.kie.api.definition.type.Label("MeasureName")
	private java.lang.String measure;

	@org.kie.api.definition.type.Label("Status")
	private java.lang.String status;

	@org.kie.api.definition.type.Label("OverReadRequired")
	private java.lang.Integer overrequired;

	@org.kie.api.definition.type.Label("Action")
	private java.lang.String action;

	@org.kie.api.definition.type.Label("Counter")
	private java.lang.Integer counter;

	@org.kie.api.definition.type.Label(value = "assignedTo")
	private java.lang.String assignedTo;

	public Chase() {
	}

	public java.lang.String getMember() {
		return this.member;
	}

	public void setMember(java.lang.String member) {
		this.member = member;
	}

	public java.lang.String getMeasure() {
		return this.measure;
	}

	public void setMeasure(java.lang.String measure) {
		this.measure = measure;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.Integer getOverrequired() {
		return this.overrequired;
	}

	public void setOverrequired(java.lang.Integer overrequired) {
		this.overrequired = overrequired;
	}

	public java.lang.String getAction() {
		return this.action;
	}

	public void setAction(java.lang.String action) {
		this.action = action;
	}

	public java.lang.Integer getCounter() {
		return this.counter;
	}

	public void setCounter(java.lang.Integer counter) {
		this.counter = counter;
	}

	public java.lang.String getAssignedTo() {
		return this.assignedTo;
	}

	public void setAssignedTo(java.lang.String assignedTo) {
		this.assignedTo = assignedTo;
	}

	public Chase(java.lang.String member, java.lang.String measure,
			java.lang.String status, java.lang.Integer overrequired,
			java.lang.String action, java.lang.Integer counter,
			java.lang.String assignedTo) {
		this.member = member;
		this.measure = measure;
		this.status = status;
		this.overrequired = overrequired;
		this.action = action;
		this.counter = counter;
		this.assignedTo = assignedTo;
	}

}