package com.citiustech.mrr.signaleventpoc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LoopBO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("counter")
	private Integer counter;
	@org.kie.api.definition.type.Label("MaxLoop")
	private Integer maxLoop;

	@org.kie.api.definition.type.Label(value = "abstracterCounter")
	private java.lang.Integer abstracterCounter;

	public LoopBO() {
	}

	public java.lang.Integer getCounter() {
		return this.counter;
	}

	public void setCounter(java.lang.Integer counter) {
		this.counter = counter;
	}

	public java.lang.Integer getMaxLoop() {
		return this.maxLoop;
	}

	public void setMaxLoop(java.lang.Integer maxLoop) {
		this.maxLoop = maxLoop;
	}

	public java.lang.Integer getAbstracterCounter() {
		return this.abstracterCounter;
	}

	public void setAbstracterCounter(java.lang.Integer abstracterCounter) {
		this.abstracterCounter = abstracterCounter;
	}

	public LoopBO(java.lang.Integer counter, java.lang.Integer maxLoop,
			java.lang.Integer abstracterCounter) {
		this.counter = counter;
		this.maxLoop = maxLoop;
		this.abstracterCounter = abstracterCounter;
	}

}