package com.citiustech.mrr;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class ChaseData extends org.drools.persistence.jpa.marshaller.VariableEntity	implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "CHASEDATA_ID_GENERATOR")
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(name = "CHASEDATA_ID_GENERATOR", sequenceName = "CHASEDATA_ID_SEQ")
    @javax.persistence.Column(name = "CHSE_ID" , unique = true)
	private java.lang.Long id;

	@javax.persistence.Column(name = "RAW_CHSE_ID")
	private java.lang.Long rawChaseId;

	@javax.persistence.Column(name = "CMPG_ID")
	private java.lang.Long campaignId;

	@javax.persistence.Column(name = "MSR_ID")
	private java.lang.Long measure;

	@javax.persistence.Column(name = "MEM_ID")
	private java.lang.Long member;

	@javax.persistence.Column(name = "PRAC_ID")
	private java.lang.Long practitioner;

	@javax.persistence.Column(name = "ASSGD_TO_ID")
	private java.lang.Long assignedTo;

	@javax.persistence.Column(name = "CHSE_STS_MSTR_ID")
	private java.lang.Long chaseStatusMstrId;

	@javax.persistence.Column(name = "MSR_VER")
	private java.lang.Long measureVersion;

	@javax.persistence.Column(name = "MSR_CD")
	private java.lang.String measureCode;

	@javax.persistence.Column(name = "SUBMSR_CD")
	private java.lang.String subMeasureCode;

	@javax.persistence.Column(name = "DNRTR_QLFNG_EVNT_DT")
	private java.util.Date denomQalifyingEventDate;

	@javax.persistence.Column(name = "CHSE_DUE_DT")
	private java.util.Date endDate;

	@javax.persistence.Column(name = "CHSE_STS_MSTR_CD")
	private java.lang.String status;

	@javax.persistence.Column(name = "WRKFL_INST_ID")
	private java.lang.Long workflowInstanceid;

	@javax.persistence.Column(name = "SPOC_NM")
	private java.lang.String spocName;

	@javax.persistence.Column(name = "SPOC_PH_NO")
	private java.lang.String spocPhoneNumber;

	@javax.persistence.Column(name = "SPOC_EML_ID")
	private java.lang.String spocEmail;

	@javax.persistence.Column(name = "FLUP_DT")
	private java.util.Date followpDate;

	@javax.persistence.Column(name = "RPT_FRM_DT")
	private java.util.Date rptFromDate;

	@javax.persistence.Column(name = "RPT_TO_DT")
	private java.util.Date rptToDate;

	@javax.persistence.Column(name = "CMPG_CD")
	private java.lang.String campaign;

	@javax.persistence.Column(name = "SRVC_LOCN_ID")
	private java.lang.Long facility;

	@javax.persistence.Column(name = "VLD_FRM_DT")
	private java.util.Date vldFromDate;

	@javax.persistence.Column(name = "VLD_TO_DT")
	private java.util.Date vldToDate;

	@javax.persistence.Column(name = "DEL_FLG")
	private java.lang.Boolean delFlag;
	
	@javax.persistence.Column(name = "HLTHPLN_ID")
	private java.lang.Long healthPlanId;

    @javax.persistence.Column(name = "LOB_ID")
	private java.lang.Long lobId;

    @javax.persistence.Column(name = "PROD_ID")
	private java.lang.Long prodId;

	@javax.persistence.Column(name = "LOGIN_USER")
	private java.lang.String user;

	private java.lang.Integer overrequired;

	private java.lang.Integer counter;

	private java.lang.String action;

	public ChaseData() {
	}

	public java.lang.String getAction() {
		return this.action;
	}

	public void setAction(java.lang.String action) {
		this.action = action;
	}

	public java.lang.Long getMember() {
		return this.member;
	}

	public void setMember(java.lang.Long member) {
		this.member = member;
	}

	public java.lang.Long getFacility() {
		return this.facility;
	}

	public void setFacility(java.lang.Long facility) {
		this.facility = facility;
	}

	public java.lang.Long getMeasureVersion() {
		return this.measureVersion;
	}

	public void setMeasureVersion(java.lang.Long measureVersion) {
		this.measureVersion = measureVersion;
	}

	public java.lang.String getMeasureCode() {
		return this.measureCode;
	}

	public void setMeasureCode(java.lang.String measureCode) {
		this.measureCode = measureCode;
	}

	public java.lang.Long getPractitioner() {
		return this.practitioner;
	}

	public void setPractitioner(java.lang.Long practitioner) {
		this.practitioner = practitioner;
	}

	public java.lang.String getSubMeasureCode() {
		return this.subMeasureCode;
	}

	public void setSubMeasureCode(java.lang.String subMeasureCode) {
		this.subMeasureCode = subMeasureCode;
	}

	public java.util.Date getDenomQalifyingEventDate() {
		return this.denomQalifyingEventDate;
	}

	public void setDenomQalifyingEventDate(
			java.util.Date denomQalifyingEventDate) {
		this.denomQalifyingEventDate = denomQalifyingEventDate;
	}

	public java.util.Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(java.util.Date endDate) {
		this.endDate = endDate;
	}

	public java.lang.Long getWorkflowInstanceid() {
		return this.workflowInstanceid;
	}

	public void setWorkflowInstanceid(java.lang.Long workflowInstanceid) {
		this.workflowInstanceid = workflowInstanceid;
	}

	public java.lang.String getSpocName() {
		return this.spocName;
	}

	public void setSpocName(java.lang.String spocName) {
		this.spocName = spocName;
	}

	public java.lang.String getSpocPhoneNumber() {
		return this.spocPhoneNumber;
	}

	public void setSpocPhoneNumber(java.lang.String spocPhoneNumber) {
		this.spocPhoneNumber = spocPhoneNumber;
	}

	public java.lang.String getSpocEmail() {
		return this.spocEmail;
	}

	public void setSpocEmail(java.lang.String spocEmail) {
		this.spocEmail = spocEmail;
	}

	public java.util.Date getFollowpDate() {
		return this.followpDate;
	}

	public void setFollowpDate(java.util.Date followpDate) {
		this.followpDate = followpDate;
	}

	public java.util.Date getRptFromDate() {
		return this.rptFromDate;
	}

	public void setRptFromDate(java.util.Date rptFromDate) {
		this.rptFromDate = rptFromDate;
	}

	public java.util.Date getRptToDate() {
		return this.rptToDate;
	}

	public void setRptToDate(java.util.Date rptToDate) {
		this.rptToDate = rptToDate;
	}

	public java.lang.String getCampaign() {
		return this.campaign;
	}

	public void setCampaign(java.lang.String campaign) {
		this.campaign = campaign;
	}

	public java.lang.String getUser() {
		return this.user;
	}

	public void setUser(java.lang.String user) {
		this.user = user;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.Integer getOverrequired() {
		return this.overrequired;
	}

	public void setOverrequired(java.lang.Integer overrequired) {
		this.overrequired = overrequired;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Integer getCounter() {
		return this.counter;
	}

	public void setCounter(java.lang.Integer counter) {
		this.counter = counter;
	}

	public java.lang.Long getAssignedTo() {
		return this.assignedTo;
	}

	public void setAssignedTo(java.lang.Long assignedTo) {
		this.assignedTo = assignedTo;
	}

	public java.lang.Long getRawChaseId() {
		return this.rawChaseId;
	}

	public void setRawChaseId(java.lang.Long rawChaseId) {
		this.rawChaseId = rawChaseId;
	}

	public java.lang.Long getCampaignId() {
		return this.campaignId;
	}

	public void setCampaignId(java.lang.Long campaignId) {
		this.campaignId = campaignId;
	}

	public java.lang.Long getMeasure() {
		return this.measure;
	}

	public void setMeasure(java.lang.Long measure) {
		this.measure = measure;
	}

	public java.lang.Long getChaseStatusMstrId() {
		return this.chaseStatusMstrId;
	}

	public void setChaseStatusMstrId(java.lang.Long chaseStatusMstrId) {
		this.chaseStatusMstrId = chaseStatusMstrId;
	}

	public java.util.Date getVldFromDate() {
		return this.vldFromDate;
	}

	public void setVldFromDate(java.util.Date vldFromDate) {
		this.vldFromDate = vldFromDate;
	}

	public java.util.Date getVldToDate() {
		return this.vldToDate;
	}

	public void setVldToDate(java.util.Date vldToDate) {
		this.vldToDate = vldToDate;
	}

	public java.lang.Boolean getDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(java.lang.Boolean delFlag) {
		this.delFlag = delFlag;
	}

	public java.lang.Long getHealthPlanId() {
		return this.healthPlanId;
	}

	public void setHealthPlanId(java.lang.Long healthPlanId) {
		this.healthPlanId = healthPlanId;
	}

	public java.lang.Long getLobId() {
		return this.lobId;
	}

	public void setLobId(java.lang.Long lobId) {
		this.lobId = lobId;
	}

	public java.lang.Long getProdId() {
		return this.prodId;
	}

	public void setProdId(java.lang.Long prodId) {
		this.prodId = prodId;
	}

	public ChaseData(java.lang.Long id, java.lang.Long rawChaseId,
			java.lang.Long campaignId, java.lang.Long measure,
			java.lang.Long member, java.lang.Long practitioner,
			java.lang.Long assignedTo, java.lang.Long chaseStatusMstrId,
			java.lang.Long measureVersion, java.lang.String measureCode,
			java.lang.String subMeasureCode,
			java.util.Date denomQalifyingEventDate, java.util.Date endDate,
			java.lang.String status, java.lang.Long workflowInstanceid,
			java.lang.String spocName, java.lang.String spocPhoneNumber,
			java.lang.String spocEmail, java.util.Date followpDate,
			java.util.Date rptFromDate, java.util.Date rptToDate,
			java.lang.String campaign, java.lang.Long facility,
			java.util.Date vldFromDate, java.util.Date vldToDate,
			java.lang.Boolean delFlag, java.lang.String user,
			java.lang.Integer overrequired, java.lang.Integer counter,
			java.lang.String action, java.lang.Long healthPlanId,
			java.lang.Long lobId, java.lang.Long prodId) {
		this.id = id;
		this.rawChaseId = rawChaseId;
		this.campaignId = campaignId;
		this.measure = measure;
		this.member = member;
		this.practitioner = practitioner;
		this.assignedTo = assignedTo;
		this.chaseStatusMstrId = chaseStatusMstrId;
		this.measureVersion = measureVersion;
		this.measureCode = measureCode;
		this.subMeasureCode = subMeasureCode;
		this.denomQalifyingEventDate = denomQalifyingEventDate;
		this.endDate = endDate;
		this.status = status;
		this.workflowInstanceid = workflowInstanceid;
		this.spocName = spocName;
		this.spocPhoneNumber = spocPhoneNumber;
		this.spocEmail = spocEmail;
		this.followpDate = followpDate;
		this.rptFromDate = rptFromDate;
		this.rptToDate = rptToDate;
		this.campaign = campaign;
		this.facility = facility;
		this.vldFromDate = vldFromDate;
		this.vldToDate = vldToDate;
		this.delFlag = delFlag;
		this.user = user;
		this.overrequired = overrequired;
		this.counter = counter;
		this.action = action;
		this.healthPlanId = healthPlanId;
		this.lobId = lobId;
		this.prodId = prodId;
	}




}