package com.citiustech.mrr.sample;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class ABS_PROV implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "ABS_PROV_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "ABS_PROV_ID_GENERATOR", sequenceName = "ABS_PROV_ID_SEQ")
	@javax.persistence.Column(name= "ABS_ID")
	private java.lang.Long absId;

	@javax.persistence.Column(name= "CMM_ID")
	private java.lang.Long cmmId;

	@javax.persistence.Column(name= "CPMM_ID")
	private java.lang.Long cpmmId;

	@javax.persistence.Column(name= "STATUS")
	private java.lang.String status;

	@javax.persistence.Column(name= "PROV_ID")
	private java.lang.Long provId;

	public ABS_PROV() {
	}

	public java.lang.Long getAbsId() {
		return this.absId;
	}

	public void setAbsId(java.lang.Long absId) {
		this.absId = absId;
	}

	public java.lang.Long getCmmId() {
		return this.cmmId;
	}

	public void setCmmId(java.lang.Long cmmId) {
		this.cmmId = cmmId;
	}

	public java.lang.Long getCpmmId() {
		return this.cpmmId;
	}

	public void setCpmmId(java.lang.Long cpmmId) {
		this.cpmmId = cpmmId;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.Long getProvId() {
		return this.provId;
	}

	public void setProvId(java.lang.Long provId) {
		this.provId = provId;
	}

	public ABS_PROV(java.lang.Long absId, java.lang.Long cmmId,
			java.lang.Long cpmmId, java.lang.String status,
			java.lang.Long provId) {
		this.absId = absId;
		this.cmmId = cmmId;
		this.cpmmId = cpmmId;
		this.status = status;
		this.provId = provId;
	}

}