package com.citiustech.mrr.sample;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class CMM implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "CMM_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "CMM_ID_GENERATOR", sequenceName = "CMM_ID_SEQ")
	@javax.persistence.Column(name = "CMM_ID")
	private java.lang.Long cmmId;

	@javax.persistence.Column(name = "CMM_CHSE_CD")
	private java.lang.String cmmChseCd;

	@javax.persistence.Column(name = "MEM_ID")
	private java.lang.Long memId;

	@javax.persistence.Column(name = "CMPG_CD")
	private java.lang.String cmpgCd;

	@javax.persistence.Column(name = "MSR_VER")
	private java.lang.String msrVer;

	@javax.persistence.Column(name = "MSR_CD")
	private java.lang.String msrCd;

	@javax.persistence.Column(name = "SUBMSR_CD")
	private java.lang.String submsrCd;

	@javax.persistence.Column(name = "CMM_CHSE_STS")
	private java.lang.String cmmChseSts;

	@javax.persistence.Column(name = "ASSGD_TO_LGN_ID")
	private java.lang.String assgdToLgnId;

	@javax.persistence.Column(name = "RAW_CHSE_ID")
	private java.lang.Long rawChseId;

	@javax.persistence.Column(name = "CHSE_DUE_DT")
	private java.util.Date chseDueDt;

	@javax.persistence.Transient
	private java.util.List<com.citiustech.mrr.sample.CPMM> cpmmList;

	//@javax.persistence.ManyToOne(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	@javax.persistence.Column(name = "ABS_PROV")
	private com.citiustech.mrr.sample.ABS_PROV absProv;

	public CMM() {
	}

	public java.lang.Long getCmmId() {
		return this.cmmId;
	}

	public void setCmmId(java.lang.Long cmmId) {
		this.cmmId = cmmId;
	}

	public java.lang.String getCmmChseCd() {
		return this.cmmChseCd;
	}

	public void setCmmChseCd(java.lang.String cmmChseCd) {
		this.cmmChseCd = cmmChseCd;
	}

	public java.lang.Long getMemId() {
		return this.memId;
	}

	public void setMemId(java.lang.Long memId) {
		this.memId = memId;
	}

	public java.lang.String getCmpgCd() {
		return this.cmpgCd;
	}

	public void setCmpgCd(java.lang.String cmpgCd) {
		this.cmpgCd = cmpgCd;
	}

	public java.lang.String getMsrVer() {
		return this.msrVer;
	}

	public void setMsrVer(java.lang.String msrVer) {
		this.msrVer = msrVer;
	}

	public java.lang.String getMsrCd() {
		return this.msrCd;
	}

	public void setMsrCd(java.lang.String msrCd) {
		this.msrCd = msrCd;
	}

	public java.lang.String getSubmsrCd() {
		return this.submsrCd;
	}

	public void setSubmsrCd(java.lang.String submsrCd) {
		this.submsrCd = submsrCd;
	}

	public java.lang.String getCmmChseSts() {
		return this.cmmChseSts;
	}

	public void setCmmChseSts(java.lang.String cmmChseSts) {
		this.cmmChseSts = cmmChseSts;
	}

	public java.lang.String getAssgdToLgnId() {
		return this.assgdToLgnId;
	}

	public void setAssgdToLgnId(java.lang.String assgdToLgnId) {
		this.assgdToLgnId = assgdToLgnId;
	}

	public java.lang.Long getRawChseId() {
		return this.rawChseId;
	}

	public void setRawChseId(java.lang.Long rawChseId) {
		this.rawChseId = rawChseId;
	}

	public java.util.Date getChseDueDt() {
		return this.chseDueDt;
	}

	public void setChseDueDt(java.util.Date chseDueDt) {
		this.chseDueDt = chseDueDt;
	}

	public java.util.List<com.citiustech.mrr.sample.CPMM> getCpmmList() {
		return this.cpmmList;
	}

	public void setCpmmList(
			java.util.List<com.citiustech.mrr.sample.CPMM> cpmmList) {
		this.cpmmList = cpmmList;
	}

	public com.citiustech.mrr.sample.ABS_PROV getAbsProv() {
		return this.absProv;
	}

	public void setAbsProv(com.citiustech.mrr.sample.ABS_PROV absProv) {
		this.absProv = absProv;
	}

	public CMM(java.lang.Long cmmId, java.lang.String cmmChseCd,
			java.lang.Long memId, java.lang.String cmpgCd,
			java.lang.String msrVer, java.lang.String msrCd,
			java.lang.String submsrCd, java.lang.String cmmChseSts,
			java.lang.String assgdToLgnId, java.lang.Long rawChseId,
			java.util.Date chseDueDt,
			java.util.List<com.citiustech.mrr.sample.CPMM> cpmmList,
			com.citiustech.mrr.sample.ABS_PROV absProv) {
		this.cmmId = cmmId;
		this.cmmChseCd = cmmChseCd;
		this.memId = memId;
		this.cmpgCd = cmpgCd;
		this.msrVer = msrVer;
		this.msrCd = msrCd;
		this.submsrCd = submsrCd;
		this.cmmChseSts = cmmChseSts;
		this.assgdToLgnId = assgdToLgnId;
		this.rawChseId = rawChseId;
		this.chseDueDt = chseDueDt;
		this.cpmmList = cpmmList;
		this.absProv = absProv;
	}

}