package com.citiustech.mrr.sample;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MRR implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer counter;
	private java.lang.Integer eval;

	public MRR() {
	}

	public java.lang.Integer getCounter() {
		return this.counter;
	}

	public void setCounter(java.lang.Integer counter) {
		this.counter = counter;
	}

	public java.lang.Integer getEval() {
		return this.eval;
	}

	public void setEval(java.lang.Integer eval) {
		this.eval = eval;
	}

	public MRR(java.lang.Integer counter, java.lang.Integer eval) {
		this.counter = counter;
		this.eval = eval;
	}

}