package com.citiustech.mrr;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Chase implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Member")
	private java.lang.String member;

	@org.kie.api.definition.type.Label(value = "Measure")
	private java.lang.String measure;

	@org.kie.api.definition.type.Label(value = "Gap")
	private java.lang.String gap;

	@org.kie.api.definition.type.Label(value = "Provider")
	private java.lang.String provider;

	@org.kie.api.definition.type.Label(value = "Status")
	private java.lang.String status;

	public Chase() {
	}

	public java.lang.String getMember() {
		return this.member;
	}

	public void setMember(java.lang.String member) {
		this.member = member;
	}

	public java.lang.String getMeasure() {
		return this.measure;
	}

	public void setMeasure(java.lang.String measure) {
		this.measure = measure;
	}

	public java.lang.String getGap() {
		return this.gap;
	}

	public void setGap(java.lang.String gap) {
		this.gap = gap;
	}

	public java.lang.String getProvider() {
		return this.provider;
	}

	public void setProvider(java.lang.String provider) {
		this.provider = provider;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public Chase(java.lang.String member, java.lang.String measure,
			java.lang.String gap, java.lang.String provider,
			java.lang.String status) {
		this.member = member;
		this.measure = measure;
		this.gap = gap;
		this.provider = provider;
		this.status = status;
	}

}